remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Extropy Business Automation
description: Extropy is a company that aims to help people and organizations to take adventage of technology to automate or improve process.

show_downloads: false
